import os
import logging
import textwrap
import asyncio
from groq import Groq

from utils.gitlab_api import get_mr_diff, post_comment_to_mr

logger = logging.getLogger(__name__)

MIXTRAL_MODEL = "mixtral-8x7b-32768"
DEEPSEEK_MODEL = "deepseek-coder-v2-lite-base"


def get_groq_client():
    """Lazy-load Groq client so Render env vars are available."""
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.error("❌ GROQ_API_KEY is missing! AI review cannot run.")
        return None
    return Groq(api_key=api_key)


def _groq_sync(model: str, prompt: str) -> str:
    """Sync API call (Groq SDK is sync-only). Uses lazy client."""
    client = get_groq_client()
    if not client:
        return "GROQ_API_KEY missing — AI could not run."

    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a professional code reviewer."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=1200,
        )
        return resp.choices[0].message.content.strip()

    except Exception as e:
        logger.error(f"Groq API error: {e}")
        return f"Groq API error: {e}"


async def _groq(model: str, prompt: str) -> str:
    """Async wrapper around sync Groq call."""
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(None, _groq_sync, model, prompt)


async def review_merge_request(project_id, mr_iid, diff, source_branch="main"):
    logger.info(f"Running AI review for MR !{mr_iid}")

    # Fetch diff if missing
    if not diff or len(diff) < 20:
        logger.info("Diff missing, fetching from GitLab API...")
        diff = await get_mr_diff(project_id, mr_iid)

    if not diff:
        await post_comment_to_mr(project_id, mr_iid, "⚠️ Could not retrieve diff.")
        return

    truncated = diff[:15000]

    summary_prompt = f"""
    You are analyzing a GitLab Merge Request diff.

    Diff:
    ```diff
    {truncated}
    ```

    Produce a short, clear summary (3–6 bullet points).
    """

    detailed_prompt = f"""
    You are a senior code reviewer.

    Review this diff:
    ```diff
    {truncated}
    ```

    Provide:
    - bug risks  
    - logic issues  
    - security concerns  
    - readability + structure improvements  
    - performance suggestions  
    - constructive tone  
    """

    # Generate summary via Mixtral
    summary = await _groq(MIXTRAL_MODEL, summary_prompt)

    # Generate detailed analysis via DeepSeek
    detailed = await _groq(DEEPSEEK_MODEL, detailed_prompt)

    body = f"""
### 🤖 AgentOps AI Code Review

#### 📝 Summary (Mixtral)
{summary}

---

#### 🔍 Detailed Review (DeepSeek Coder)
{detailed}

---

_Review generated by AgentOps (Groq)._
"""

    await post_comment_to_mr(project_id, mr_iid, body)
    logger.info("AI review posted successfully.")
